// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteCredentials() {
  return window['go']['main']['App']['DeleteCredentials']();
}

export function LoadPasswd() {
  return window['go']['main']['App']['LoadPasswd']();
}

export function LoadUsername() {
  return window['go']['main']['App']['LoadUsername']();
}

export function SaveCredentials(arg1, arg2) {
  return window['go']['main']['App']['SaveCredentials'](arg1, arg2);
}
