// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadPasswd():Promise<string>;

export function LoadUsername():Promise<string>;

export function SaveCredentials(arg1:string,arg2:string):Promise<void>;
